var path = require('path');
var webpack = require('webpack');

module.exports = {
    context: path.resolve('js'),
    entry: './app.js',
    output: {
        path: path.resolve('dist/'),
        publicPath: '/public/assets/',
        filename: 'bundle.js'
    },

    devServer: {
        contentBase: 'public'
    },

    watch: false,

    plugins: [
        new webpack.BannerPlugin('*******************\nGenerated by webpack\n*******************\n')
    ],

    module: {
            loaders: [
                {
                    test: /\.css$/,
                    exclude: /node_modules/,
                    loader: 'style-loader!css-loader'
                },
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel-loader',
                    query: {
                     presets: ['latest']
                    }
                },
                {
                    test: /\.(png|jpg|ttf|eot)/,
                    exclude: /node_modules/,
                    loader: 'url-loader?limit=10000'
                },
                { loader: 'raw', test: /\.(css|html)$/ },
                {
                    test: /\.(eot|svg|ttf|woff|woff2)$/,
                    exclude: /node_modules/,
                    loader: 'file?name=public/fonts/[name].[ext]'
                }
             ]
     }
};